[package]
name = "yes-rs"
version = "0.1.0"
edition = "2024"
authors = ["John Doe <foo@email.tld>"]
description = "yes"
license = "MIT OR Apache-2.0"
repository = "https://github.com/upset-c-developers/yes-rs"
readme = "README.md"
categories = ["command-line-utilities", "development-tools"]
